AWS_REGION_NAME = 'us-east-1'
LOG_FORMAT = '%(asctime)s - %(name)s - [%(levelname)s] - %(message)s'
TIME_FORMAT = '%Y-%m-%d %H:%M:%S'
VOTING_INFO_TABLE = 'voting_info'
CANDIDATE_VOTES_TABLE = 'Candidate_Votes'
END_VOTE_LAMBDA = 'endVoteTestFunc'
LAMBDA_ARN = 'arn:aws:lambda:us-east-1:620370720330:function:endVoteTestFunc'
