AWS_REGION_NAME = 'us-east-1'
LOG_FORMAT = '%(asctime)s - %(name)s - [%(levelname)s] - %(message)s'
TIME_FORMAT = '%Y-%m-%d %H:%M:%S'
VOTING_INFO_TABLE = 'voting_info'
VOTER_INFO_TABLE='voter_data'
AWS_REGION_NAME = 'us-east-1'
S3_bucket_name = "ece1779-a3-test1"
ACCESS_KEY = "AKIARYPZNG6KRLLMQZ3X"
SECRET_KEY = "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"
